# Use the official Redis base image from Docker Hub
FROM redis:latest

# Expose the default Redis port (6379) to allow external access
EXPOSE 6379

# Set a custom Redis configuration file if needed (optional)
# COPY redis.conf /usr/local/etc/redis/redis.conf
# CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]